Add videolink attribute to recipes
knowde-academy/team-1-fe-react pull request #20
Opened 2021-09-08 12:01 UTC by TomaszLaski

2021-09-09 07:28 UTC, Aliath requested changes

2021-09-09 07:28 UTC, Aliath commented on src/components/RecipeForm/RecipeForm.tsx
> +  defaultValue?: any;
Get rid of `any`

2021-09-09 07:28 UTC, Aliath commented on src/components/AddRecipe/AddRecipe.tsx
> +              The recipe was created!.
Remove exclamation mark

2021-09-09 07:28 UTC, Aliath commented on src/components/RecipeUpdate/RecipeUpdate.tsx
> +  const [responseState, setResponseState] = useState<
Change namings to `updateResponseState`, `fetchResponseState`

2021-09-09 07:28 UTC, Aliath commented on src/components/RecipeUpdate/RecipeUpdate.tsx
> +  }, [id]);
`React Hook useEffect has a missing dependency: 'setDataRecipes'. Either include it or remove the dependency array. If 'setDataRecipes' changes too often, find the parent component that defines it and wrap that definition in useCallback`

2021-09-09 07:28 UTC, Aliath commented on src/components/RecipeUpdate/RecipeUpdate.tsx
> +                The recipe was updated!.
Remove exclamation mark

2021-09-09 07:28 UTC, Aliath commented on src/components/RecipeDetails/RecipeDetails.tsx
> +          setDataRecipes={setDataRecipes}
Change it to `onUpdate={onUpdate}` and then fetch details once again

2021-09-09 07:28 UTC, Aliath commented on src/components/RecipeDetails/RecipeDetails.tsx
> +          setDataRecipes={setDataRecipes}
Btw. `setDataRecipes` -> `setRecipeDetails`

2021-09-09 07:28 UTC, Aliath commented on src/components/RecipeDetails/RecipeDetails.tsx
> +  const [recipeUpdated, setRecipeUpdated] = useState<'updated' | 'waiting'>(
Keep it similar across all request states - `recipeUpdateState<'loading' | 'idle'>`

2021-09-09 09:50 UTC, TomaszLaski commented on src/components/RecipeForm/RecipeForm.tsx
> +  defaultValue?: any;
Unfortunately, I lack TS skills to fix this problem despite several hours of trying

2021-09-14 08:13 UTC, Aliath approved these changes

2021-09-14 08:16 UTC, merged