Detailedview
knowde-academy/team-1-fe-react pull request #4
Opened 2021-08-18 11:47 UTC by KBus9455

Add Detailed View Component.

2021-08-18 18:30 UTC, Aliath requested changes
Good job! I have listed some things that can be done just better - please take a look on it

2021-08-18 18:30 UTC, Aliath commented on src/Router.tsx
> +        <DetailedView />
`DetailedView` is not as explicit as it can be 😄  What about to rename it to `RecipeDetails`?

2021-08-18 18:30 UTC, Aliath commented on src/components/DetailedView/DetailedView.scss
> +body {
Well if you want to style whole the `body` element you shall do it in correct place: `src/assets/styles/index.scss` - there's the file that contains global styles

2021-08-18 18:30 UTC, Aliath commented on src/components/DetailedView/DetailedView.scss
> +h1 {
Do not style by elements - use classes instead

2021-08-18 18:30 UTC, Aliath commented on src/components/DetailedView/DetailedView.tsx
> +  const { id } = useParams<{ id: string }>();
Nice one! 😎

2021-08-18 18:30 UTC, Aliath commented on src/components/DetailedView/DetailedView.tsx
> +          {String(dataRecipes!.name) !== 'unknown' && (
I guess `String(...)` wrapper is not required 🤔

2021-08-18 18:30 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +                <ListItem alignItems="flex-start" key={recipe.id}>
If you add `key` property to `<Link>` component you can remove it in `<ListItem>`

2021-08-18 18:30 UTC, Aliath commented on src/services/recipes.ts
> +  console.log('hej', res.data);
console 👀

2021-08-18 18:30 UTC, Aliath commented on src/components/DetailedView/DetailedView.scss
> +.buttonBack {
Let's keep [kebab-case](https://www.theserverside.com/definition/Kebab-case) namings

2021-08-18 19:22 UTC, KBus9455 commented on src/components/DetailedView/DetailedView.tsx
> +          {String(dataRecipes!.name) !== 'unknown' && (
If there is no String wrapper i have this error: "This condition will always return 'true' since the types 'number | undefined' and 'string' have no overlap.ts(2367)"

2021-08-19 05:31 UTC, Aliath requested changes

2021-08-19 05:31 UTC, Aliath commented on src/Router.tsx
> +import { RecipeDetails } from 'components/RecipeDetails/RecipeDetails';
If you create `components/RecipeDetails/index.ts` with following content:
```
export * from './RecipeDetails'
```

you can easily change this import to
```
import { RecipeDetails } from 'components/RecipeDetails';
```

2021-08-19 05:31 UTC, Aliath commented on src/components/RecipeDetails/RecipeDetails.scss
> +* {
Global styles should be placed inside `src/assets/styles/index.scss`

2021-08-19 05:31 UTC, Aliath commented on src/components/RecipeDetails/RecipeDetails.tsx
> +  }, []);
`React Hook useEffect has a missing dependency: 'id'. Either include it or remove the dependency array`

If you would add `id` to the dependency it will react automatically on route change f.e. `/recipes/1` to `/recipes/2` and fetch the data one again. That's a good practice 😄

2021-08-19 05:31 UTC, Aliath commented on src/components/RecipeDetails/RecipeDetails.tsx
> +    return <div>No recipe</div>;
What about `<Alert>` [component](https://material-ui.com/components/alert/)?

2021-08-19 05:31 UTC, Aliath commented on src/components/RecipeDetails/RecipeDetails.tsx
> +    return <div>Loading</div>;
What about [spinner component](https://material-ui.com/components/progress/)?

2021-08-19 05:31 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
>            {recipes.map((recipe: any) => {
`any` 👀

2021-08-19 07:17 UTC, KBus9455 commented on src/Router.tsx
> +import { RecipeDetails } from 'components/RecipeDetails/RecipeDetails';
changed

2021-08-19 07:23 UTC, KBus9455 commented on src/components/RecipeDetails/RecipeDetails.scss
> +* {
changed

2021-08-19 07:46 UTC, KBus9455 commented on src/components/RecipeDetails/RecipeDetails.tsx
> +    return <div>Loading</div>;
added

2021-08-19 07:46 UTC, KBus9455 commented on src/components/RecipeDetails/RecipeDetails.tsx
> +    return <div>No recipe</div>;
added

2021-08-19 09:07 UTC, Aliath requested changes

2021-08-19 09:07 UTC, Aliath commented on src/components/RecipeDetails/RecipeDetails.tsx
> +const useStylesAlert = makeStyles((theme: Theme) =>
You can create different fields in one styles object:

```suggestion
const useStyles = makeStyles((theme: Theme) => 
  createStyles({
    spinner: {
      width: '100%',
      '& > * + *': {
        marginTop: theme.spacing(2),
      },
    },
    anyOtherClass: {
      width: '100%',
      '& > * + *': {
        marginTop: theme.spacing(2),
      },
    },
  })
)
```

2021-08-19 09:07 UTC, Aliath commented on src/components/RecipeDetails/RecipeDetails.tsx
> +        <CircularProgress />
There should be only only one spinner 😄

2021-08-19 10:28 UTC, KBus9455 commented on src/components/RecipeDetails/RecipeDetails.tsx
> +const useStylesAlert = makeStyles((theme: Theme) =>
Ok, i changed, everything is one field

2021-08-19 15:30 UTC, KBus9455 commented on src/components/RecipeDetails/RecipeDetails.tsx
> +  }, []);
changed :)

2021-08-23 08:46 UTC, merged