Add pagination to recipes
knowde-academy/team-1-fe-react pull request #5
Opened 2021-08-18 12:32 UTC by TomaszLaski

added pagination, it is inside RecipesList folder becouse for now it is not suitable for reusability; add bootstrap for styles; changed component structure and added simple loader

2021-08-18 18:38 UTC, Aliath requested changes

2021-08-18 18:38 UTC, Aliath commented on package.json
> +    "bootstrap": "^5.1.0",
Huh, once `material-ui` is picked as UI library we should not mix it with bootstrap

2021-08-18 18:38 UTC, Aliath commented on src/components/RecipesList/RecipesDownloader.tsx
> +interface Props {
`Props` is not enough specific

2021-08-18 18:38 UTC, Aliath commented on src/components/RecipesList/RecipesDownloader.tsx
> +interface Props {
```suggestion
interface RecipesDownloaderProps {
```

2021-08-18 18:38 UTC, Aliath commented on src/components/RecipesList/RecipesDownloader.tsx
> +export const RecipesDownloader: React.FC<Props> = ({ loading, recipes }) => {
`Downloader` sounds like it download some file on user computer - rename it

2021-08-18 18:38 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +        <form>
If you will never submit this form it probably should not be a form 😄

2021-08-18 18:38 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +          <input
What about [this](https://material-ui.com/components/pagination/)?

2021-08-18 18:38 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +        <RecipesDownloader loading={loading} recipes={currentRecipes} />
Can you explain me what actually `RecipesDownloader` is used for?

2021-08-18 18:38 UTC, Aliath commented on src/components/RecipesList/RecipesPagination.tsx
> +const RecipesPagination: React.FC<Props> = ({
I don't think that custom pagination is something that we want to use:
- we have material-ui component dedicated for this
- we have to test custom component if it works well
- we should care about pages generating (for loop) when you actually do not have to 😎

2021-08-18 18:38 UTC, Aliath commented on src/components/RecipesList/RecipesPagination.tsx
> +export default RecipesPagination;
What is the target of `export default` over here? 😄

2021-08-18 18:38 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +      '& > * + *': {
selector specifity? 🧐

2021-08-18 18:38 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
>    }, []);
`getData` is missing in dependency array

2021-08-18 18:59 UTC, TomaszLaski commented on src/components/RecipesList/RecipesList.tsx
> +        <RecipesDownloader loading={loading} recipes={currentRecipes} />
"downloading" recipes from api, I couldn't think of another name, I didn't want to waste time thinking about it, so I called it that way.

2021-08-18 19:05 UTC, TomaszLaski commented on src/components/RecipesList/RecipesList.tsx
> +      '& > * + *': {
actually I got this from material ui example : https://codesandbox.io/s/y9rpj?file=/demo.tsx

2021-08-19 05:23 UTC, Aliath requested changes

2021-08-19 05:23 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +          count={Math.ceil(allRecipes / recipesPerPage)}
Let's define it as const before `return` statement - for example:
```tsx
const totalPages = Math.ceil(allRecipes / recipesPerPage);
// ...
<Pagination
          count={totalPages}
```

2021-08-19 05:23 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +          <input
👀

2021-08-19 05:23 UTC, Aliath commented on src/components/RecipesList/RecipesListFetcher.tsx
> +interface Props {
`Props` is not enough specific

2021-08-19 05:23 UTC, Aliath commented on src/components/RecipesList/RecipesListFetcher.tsx
> +export const RecipesListFetcher: React.FC<Props> = ({ loading, recipes }) => {
Actually it does not fetch recipes 😄 I think this piece of code (whole component) should be inside `RecipesList.tsx`

2021-08-19 05:23 UTC, Aliath commented on src/components/RecipesList/RecipesListFetcher.tsx
> +      {recipes.map((recipe: any) => {
`any` 👀

2021-08-19 07:31 UTC, Aliath requested changes

2021-08-19 07:31 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +          onChange={(e, value: React.SetStateAction<number>) =>
There's no need to specify type of `value` - it should be inferred

2021-08-19 07:31 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
>      const recipesList = await getRecipes();
What about to wrap `getRecipes` with try/catch blocks? Thanks to it your state can be more explicit.

Let's assume that http request failed - you have to show a feedback about it. So you can create a state that will store state of request: `loading`, `success`, `failure`

Please take a look [on it](https://github.com/knowde-academy/team-1-fe-react/pull/4/files#diff-59d27d293b14d8e5ad67f81192cdc3e750c553a0b1f32165586f333e37468d79R44)

2021-08-19 09:03 UTC, Aliath requested changes

2021-08-19 09:03 UTC, Aliath commented on src/components/RecipesList/RecipesList.tsx
> +  if (requestState === 'loading' || requestState === 'error') {
Why does `error` state displays spinner instead of negative feedback? 😄

2021-08-19 12:41 UTC, Aliath approved these changes

2021-08-19 13:30 UTC, merged